url: "https://www.patcanella.com"
baseurl: ""
permalink: pretty

# Make sure Jekyll does NOT touch your Astro SOURCE
exclude:
  - classicmode-src/
  - classicmode-src/**    # belt & suspenders
  - node_modules/
  - .astro/
  - dist/
  - "**/*.astro"          # ignore any stray .astro files anywhere
  - package.json
  - package-lock.json
  - README.md
  - .gitignore

# DO NOT include: classicmode
# Jekyll will copy the built /classicmode folder as static files by default.

plugins:
  - jekyll-sitemap
  - jekyll-feed
