# _config.yml (at the root of the branch GitHub Pages publishes)

# Site settings
url: "https://www.patcanella.com"   # your custom domain
baseurl: ""                         # user/ORG site → leave empty
permalink: pretty

# Make sure the Astro build folder is included in the Jekyll build
include:
  - classicmode

# Keep dev-only stuff out of the published site
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .astro
  - dist
  - classicmode-src   # if you use a split source/output setup

# (optional) GitHub Pages–safe plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
